#!/bin/bash

main() {
  echo "Installing brew..."
  install_linuxbrew
  echo "Installing Node..."
  install_node
  install_npm
}

install_linuxbrew() {
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
  PATH="$HOME/.linuxbrew/bin:$PATH"

  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
}

install_node() {
  echo 'export PATH=$HOME/local/bin:$PATH' >> ~/.bash_profile
  . ~/.bash_profile
  mkdir ~/local
  mkdir ~/node-latest-install
  cd ~/node-latest-install
  curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
  ./configure --prefix=~/local
  make install
  curl https://www.npmjs.org/install.sh | sh
}

install_npm() {
  npm install -g gulp bower && npm install && bower install
  bower update
}

main
