#!/bin/bash

username = ""

main() {
  echo "Initializing Polymer CLI..."
  init_polymer
  echo -e "\nCloning from repository"
  git clone https://github.com/Passageway/PassagewayWeb.git passageway-web
}

init_polymer() {
  curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  sudo apt-get install -y nodejs
  sudo ln -s /usr/bin/nodejs /usr/bin/node
  sudo npm install -g bower
  sudo npm install -g polymer-cli
  sudo npm install -g firebase-tools
}
# test() { if [ -d /usr/bin ]; then echo "what"; fi; };
main


generate_key() {
  mkdir -p .ssh
  if [ ! -f ~/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -N "" -f id_rsa
  fi
  echo "Enter your EOS username: "
  read username
  ssh-copy-id "${username}@eos22.cis.gvsu.edu"
}

add_to_config() {
    echo -e "\nHostname eos22\n    Hostname eos22.cis.gvsu.edu\n    User ${username}" >> ~/.ssh/config
}
